function checkText() {
     const inputArea = document.getElementById("Inputarea");
     const result = document.getElementById("result");

     const suspicious = [
                "\u202F", // Narrow No-Break Space
                "\u200B", // Zero Width Space
                "\u2060", // Word Joiner
                "\u00A0", // No-Break Space
                "\u200C", // Zero Width Non-Joiner
                "\u200D", // Zero Width Joiner
                "\u2061", // Function Application
                "\u2062", // Invisible Times
                "\u2063", // Invisible Separator
                "\u2064", // Invisible Plus
                "\uFEFF", // Zero Width No-Break Space (BOM)

                // zusätzliche unsichtbare/formatierende Zeichen
                "\u0009", // Tab
                "\u000A", // Line Feed (New Line)
                "\u000D", // Carriage Return

                "\u200E", // Left-to-Right Mark
                "\u200F", // Right-to-Left Mark

                "\u202A", // Left-to-Right Embedding
                "\u202B", // Right-to-Left Embedding
                "\u202C", // Pop Directional Formatting
                "\u202D", // Left-to-Right Override
                "\u202E", // Right-to-Left Override

                "\u2066", // Left-to-Right Isolate
                "\u2067", // Right-to-Left Isolate
                "\u2068", // First Strong Isolate
                "\u2069", // Pop Directional Isolate

                "\u034F", // Combining Grapheme Joiner
                "\u061C", // Arabic Letter Mark

                "\u180E"  // Mongolian Vowel Separator (deprecated)
            ];

            if(inputArea.value.trim() === ""){
                result.innerText = "Please enter some text first"
            }
            else {
                const foundCount = suspicious.filter(char => inputArea.value.includes(char)).length;
                if(foundCount > 0){
                    result.innerText = `This Text is AI Generated (${foundCount} suspicious character${foundCount > 1 ? "s" : ""} found)`;
                }
                else{
                    result.innerText = "This Text is generated by a Human"
                }
            }
}

document.getElementById("Inputarea").addEventListener("keydown", function(e) {
    if (e.key === "Enter" && e.ctrlKey) {
        checkText();
    }
});